# Generated by Django 3.0.6 on 2020-06-19 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.BigIntegerField(verbose_name='telefone')),
                ('cep', models.PositiveIntegerField(verbose_name='cep')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('produtoNome', models.CharField(blank='false', max_length=32, verbose_name='Produto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('produtoStatus', models.BooleanField(default='true', verbose_name='Produto ativo')),
                ('produtoDescricao', models.CharField(default='', max_length=320, verbose_name='Descrição')),
                ('produtoImagem', stdimage.models.StdImageField(default='core/Objetos/img-produtos/default.jpg', upload_to='core/Objetos/img-produtos', verbose_name='Imagem')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
