# Generated by Django 3.0.6 on 2020-06-20 01:25

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='produtoImagem',
            field=stdimage.models.StdImageField(upload_to='core/Objetos/img-produtos', verbose_name='Imagem'),
        ),
    ]
