# Generated by Django 3.0.5 on 2020-04-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank='false', max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contato1',
            field=models.CharField(blank='false', max_length=12, verbose_name='telefone - principal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11, unique='true', verbose_name='CPF'),
        ),
    ]
