# Generated by Django 3.0.6 on 2020-06-20 01:58

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200620_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='produtoImagem',
            field=stdimage.models.StdImageField(default='core/Objetos/img-produtos/default.jpg', upload_to='core/Objetos/img-produtos', verbose_name='Imagem'),
        ),
    ]
