# Generated by Django 3.0.6 on 2020-06-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200605_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='produtoNome',
            field=models.CharField(blank='false', max_length=32, verbose_name='Produto'),
        ),
    ]
