# Generated by Django 3.0.5 on 2020-04-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200419_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank='false', max_length=9, verbose_name='CEP'),
        ),
    ]
