# Generated by Django 3.0.6 on 2020-06-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200611_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produtoDescricao',
            field=models.CharField(default='', max_length=320, verbose_name='Descrição'),
        ),
    ]
